name: CI/CD pipelines

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/build-push-action@v3

      # Discovery Service

      - name: Build Discovery service with Maven
        run: mvn package -Dmaven.test.skip=true --file Discovery-Service/pom.xml

      - name: Push Docker Image for Discovery service
        uses: docker/build-push-action@v3
        with:
          context: ./Discovery-Service
          push: true
          platform: linux/amd64
          tag: zhmash/case-lab-java-discovery-service:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # CRM Service

      - name: Build CRM service with Maven
        run: mvn package -Dmaven.test.skip=true --file CRM/pom.xml

      - name: Push Docker Image for Discovery service
        uses: docker/build-push-action@v3
        with:
          context: ./CRM
          push: true
          platform: linux/amd64
          tag: zhmash/case-lab-java-crm:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Client Self Service

      - name: Build Client Self Service with Maven
        run: mvn package -Dmaven.test.skip=true --file Client-Self-Service/pom.xml

      - name: Push Docker Image for Discovery service
        uses: docker/build-push-action@v3
        with:
          context: ./Client-Self-Service
          push: true
          platform: linux/amd64
          tag: zhmash/case-lab-java-client-self-service:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Deploy Discovery service to Kubernetes
#        run: |
#          kubectl apply -f k8s-deployment-discovery.yml
#          kubectl rollout restart discovery-service
      
