name: CI/CD pipelines

on:
  push:
    branches:
      - master

jobs:
#  build:
#    runs-on: ubuntu-latest
#    name: Build Images
#
#    steps:
#
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#        with:
#          ref: master
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Set up Docker BuildX
#        uses: docker/setup-buildx-action@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '17'
#
#      # Discovery Service
#
#      - name: Build Discovery service with Maven
#        run: mvn package -Dmaven.test.skip=true --file Discovery-Service/pom.xml
#
#      - name: Push Docker Image for Discovery service
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: Discovery-Service/Dockerfile
#          push: true
#          tags: zhmash/case-lab-java-discovery-service:latest
#
#      # CRM Service
#
#      - name: Build CRM service with Maven
#        run: mvn package -Dmaven.test.skip=true --file CRM/pom.xml
#
#      - name: Push Docker Image for CRM service
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          file: CRM/Dockerfile
#          tags: zhmash/case-lab-java-crm:latest
#
#      # Client Self Service
#
#      - name: Build Client Self Service with Maven
#        run: mvn package -Dmaven.test.skip=true --file Client-Self-Service/pom.xml
#
#      - name: Push Docker Image for Client Self service
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          file: Client-Self-Service/Dockerfile
#          tags: zhmash/case-lab-java-client-self-service:latest

  deploy:
    runs-on: ubuntu-latest
#    needs: build
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Pull  Discovery Service Docker Image from DockerHub
        run: docker pull zhmash/case-lab-java-discovery-service:latest

      - name: Save Discovery Service Docker Image
        run: docker save -o discovery-service.tar zhmash/case-lab-java-discovery-service:latest

      - name: Remove Existing Tar File on Remote Server
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} 
          ssh ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }} 'rm -f /home/user/project/discovery-service.tar'

      - name: Copy Discovery Service Image to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./discovery-service.tar
          target: /home/user/project/discovery-service.tar

#      - name: SSH into Remote Server and Load Docker Image
#        run: ssh -i ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }} \
#          "docker load -i /path/to/destination/image.tar"

#      - name: Run Discovery Service Container on Remote Server
#        run: |
#          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }} \
#                      "docker run -d -p 8080:80 zhmash/case-lab-java-discovery-service:latest"